services:
  cable-differential-wrist:
    build: .
    environment:
      DISPLAY: $DISPLAY
      # Set ROS environment variables for the remote master
      ROS_MASTER_URI: ${ROS_MASTER_URI_SET}
      ROS_IP: ${ROS_IP_SET}
    command: roslaunch --wait cable-differential-wrist.launch rate:=0.2
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./packages/cable-differential-wrist:/root/catkin_ws/src/cable-differential-wrist
      - ./launch/cable-differential-wrist.launch:/root/catkin_ws/cable-differential-wrist.launch